USE Gym

--- donnée pour MemberShip --
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2024-04-14','2025-04-14');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2024-11-29','2025-11-29');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2025-08-10','2026-08-10');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2025-03-16','2026-03-16');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2025-05-21','2026-05-21');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2025-04-26','2026-04-26');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2025-06-10','2026-06-10');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2025-02-08','2026-02-08');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2024-08-13','2025-08-13');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2024-09-11','2025-09-11');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2025-01-02','2026-01-02');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2025-02-08','2026-02-08');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2025-02-05','2026-02-05');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2025-05-26','2026-05-26');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2025-10-19','2026-10-19');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2024-08-18','2025-08-18');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2025-06-14','2026-06-14');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2024-04-09','2025-04-09');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2024-09-15','2025-09-15');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2024-03-25','2025-03-25');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2024-10-29','2025-10-29');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2024-03-21','2025-03-21');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2025-05-24','2026-05-24');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2025-02-10','2026-02-10');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2024-10-30','2025-10-30');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2025-10-24','2026-10-24');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2025-05-09','2026-05-09');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2024-07-01','2025-07-01');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2025-02-11','2026-02-11');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2025-02-17','2026-02-17');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2024-04-03','2025-04-03');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2025-01-01','2026-01-01');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2024-09-04','2025-09-04');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2025-05-09','2026-05-09');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2024-03-27','2025-03-27');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2025-09-15','2026-09-15');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2025-06-08','2026-06-08');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2024-05-03','2025-05-03');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2024-11-23','2025-11-23');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2025-09-22','2026-09-22');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2024-11-10','2025-11-10');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2025-03-01','2026-03-01');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2025-05-25','2026-05-25');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2025-11-10','2026-11-10');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2025-07-11','2026-07-11');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2025-06-18','2026-06-18');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2025-05-29','2026-05-29');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2025-09-17','2026-09-17');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2025-10-07','2026-10-07');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2024-07-11','2025-07-11');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2025-10-25','2026-10-25');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2024-12-05','2025-12-05');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2025-04-07','2026-04-07');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2025-07-06','2026-07-06');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2024-09-09','2025-09-09');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2024-04-30','2025-04-30');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2025-09-25','2026-09-25');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2025-05-25','2026-05-25');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2024-08-22','2025-08-22');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2025-05-14','2026-05-14');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2025-02-08','2026-02-08');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2024-03-11','2025-03-11');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2025-07-01','2026-07-01');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2024-04-21','2025-04-21');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2025-04-07','2026-04-07');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2024-06-25','2025-06-25');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2025-10-23','2026-10-23');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2024-04-10','2025-04-10');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2025-02-03','2026-02-03');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2024-04-20','2025-04-20');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2025-02-07','2026-02-07');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2024-08-01','2025-08-01');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2025-06-20','2026-06-20');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2024-04-13','2025-04-13');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2024-03-24','2025-03-24');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2024-11-25','2025-11-25');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2024-09-17','2025-09-17');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2025-07-22','2026-07-22');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2024-07-31','2025-07-31');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2025-05-16','2026-05-16');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2024-03-17','2025-03-17');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2025-07-11','2026-07-11');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2024-04-20','2025-04-20');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2025-09-16','2026-09-16');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2025-09-20','2026-09-20');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2024-07-08','2025-07-08');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2025-07-10','2026-07-10');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2024-11-01','2025-11-01');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2025-04-30','2026-04-30');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2025-08-27','2026-08-27');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2025-05-07','2026-05-07');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2025-10-04','2026-10-04');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2024-09-19','2025-09-19');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2025-11-01','2026-11-01');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2024-10-19','2025-10-19');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2024-08-26','2025-08-26');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2025-09-09','2026-09-09');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2025-02-25','2026-02-25');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2024-08-01','2025-08-01');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2024-11-30','2025-11-30');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2025-01-15','2026-01-15');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2025-03-11','2026-03-11');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2024-10-12','2025-10-12');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2025-06-28','2026-06-28');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2024-05-22','2025-05-22');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2024-06-19','2025-06-19');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2025-02-12','2026-02-12');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2024-03-18','2025-03-18');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2025-11-13','2026-11-13');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2024-12-12','2025-12-12');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2025-05-05','2026-05-05');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2025-04-17','2026-04-17');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2024-03-29','2025-03-29');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2024-08-30','2025-08-30');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2024-12-16','2025-12-16');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2024-10-07','2025-10-07');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2025-06-03','2026-06-03');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2024-05-10','2025-05-10');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2025-07-16','2026-07-16');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2024-06-06','2025-06-06');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2025-10-11','2026-10-11');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2025-08-06','2026-08-06');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2024-08-05','2025-08-05');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2024-11-14','2025-11-14');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2024-09-26','2025-09-26');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2025-04-23','2026-04-23');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2024-12-26','2025-12-26');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2025-01-06','2026-01-06');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2024-03-14','2025-03-14');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2025-08-14','2026-08-14');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2024-09-08','2025-09-08');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2025-02-23','2026-02-23');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2025-10-02','2026-10-02');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2024-03-30','2025-03-30');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2025-04-11','2026-04-11');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2024-07-04','2025-07-04');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2024-09-21','2025-09-21');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2025-06-12','2026-06-12');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2024-10-02','2025-10-02');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2024-04-06','2025-04-06');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2025-11-19','2026-11-19');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2025-03-09','2026-03-09');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2024-12-09','2025-12-09');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2024-07-14','2025-07-14');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2025-08-30','2026-08-30');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2024-06-22','2025-06-22');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2025-05-03','2026-05-03');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2024-11-07','2025-11-07');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2025-09-03','2026-09-03');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2024-10-26','2025-10-26');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2024-08-09','2025-08-09');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2025-06-27','2026-06-27');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2025-07-17','2026-07-17');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2024-12-13','2025-12-13');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2024-05-26','2025-05-26');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2024-04-27','2025-04-27');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2025-07-20','2026-07-20');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2024-09-13','2025-09-13');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2025-10-14','2026-10-14');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2025-01-09','2026-01-09');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2024-06-28','2025-06-28');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2024-03-12','2025-03-12');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2025-04-15','2026-04-15');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2024-08-03','2025-08-03');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2025-08-24','2026-08-24');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2024-12-20','2025-12-20');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2025-01-20','2026-01-20');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2024-05-15','2025-05-15');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2025-11-05','2026-11-05');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2025-03-22','2026-03-22');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2024-04-17','2025-04-17');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2024-09-07','2025-09-07');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2024-07-19','2025-07-19');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2025-10-09','2026-10-09');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2024-10-24','2025-10-24');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2024-11-17','2025-11-17');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2025-05-28','2026-05-28');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2025-01-27','2026-01-27');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2024-12-29','2025-12-29');

INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2025-08-02','2026-08-02');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2024-03-16','2025-03-16');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2024-05-12','2025-05-12');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2025-07-26','2026-07-26');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2024-06-14','2025-06-14');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2024-04-05','2025-04-05');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2025-11-08','2026-11-08');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2025-02-19','2026-02-19');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2024-08-11','2025-08-11');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2025-03-04','2026-03-04');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2024-10-01','2025-10-01');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2024-07-02','2025-07-02');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2025-05-18','2026-05-18');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2024-12-01','2025-12-01');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2025-09-27','2026-09-27');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2024-11-03','2025-11-03');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2025-06-01','2026-06-01');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2024-10-15','2025-10-15');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2025-03-13','2026-03-13');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2025-07-13','2026-07-13');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2024-06-04','2025-06-04');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2025-05-30','2026-05-30');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2024-05-18','2025-05-18');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2024-09-29','2025-09-29');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2025-10-01','2026-10-01');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2024-12-22','2025-12-22');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2025-04-12','2026-04-12');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2024-03-20','2025-03-20');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2025-08-18','2026-08-18');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2024-07-28','2025-07-28');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2025-02-28','2026-02-28');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2025-09-06','2026-09-06');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2024-03-31','2025-03-31');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2024-11-22','2025-11-22');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2025-06-15','2026-06-15');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2024-08-15','2025-08-15');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2025-03-29','2026-03-29');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2024-10-05','2025-10-05');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2025-11-27','2026-11-27');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2024-06-11','2025-06-11');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2024-12-11','2025-12-11');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2025-04-19','2026-04-19');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2024-09-23','2025-09-23');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2025-05-12','2026-05-12');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2024-07-06','2025-07-06');
INSERT INTO MemberShip (DateDebutMemberShip, FinMemberShip) VALUES ('2025-08-09','2026-08-09');


---- donnée pour membres ----
insert into Membres (Nom, NomFamille, MembershipID) values ('Gustie', 'Havenhand', 1);
insert into Membres (Nom, NomFamille, MembershipID) values ('Luca', 'Tilt', 2);
insert into Membres (Nom, NomFamille, MembershipID) values ('Gabriele', 'Howarth', 3);
insert into Membres (Nom, NomFamille, MembershipID) values ('Amber', 'Gindghill', 4);
insert into Membres (Nom, NomFamille, MembershipID) values ('Che', 'Grassi', 5);
insert into Membres (Nom, NomFamille, MembershipID) values ('Milton', 'Brothers', 6);
insert into Membres (Nom, NomFamille, MembershipID) values ('Wallie', 'Islip', 7);
insert into Membres (Nom, NomFamille, MembershipID) values ('Angie', 'Besson', 8);
insert into Membres (Nom, NomFamille, MembershipID) values ('Alexis', 'Ranklin', 9);
insert into Membres (Nom, NomFamille, MembershipID) values ('Englebert', 'Sexti', 10);
insert into Membres (Nom, NomFamille, MembershipID) values ('Luisa', 'Hugnet', 11);
insert into Membres (Nom, NomFamille, MembershipID) values ('Rici', 'Minkin', 12);
insert into Membres (Nom, NomFamille, MembershipID) values ('Benjamen', 'Thirtle', 13);
insert into Membres (Nom, NomFamille, MembershipID) values ('Alix', 'Fenkel', 14);
insert into Membres (Nom, NomFamille, MembershipID) values ('Joelynn', 'Yong', 15);
insert into Membres (Nom, NomFamille, MembershipID) values ('Jolyn', 'Trevenu', 16);
insert into Membres (Nom, NomFamille, MembershipID) values ('Hartwell', 'Aymerich', 17);
insert into Membres (Nom, NomFamille, MembershipID) values ('Lloyd', 'Bridgewater', 18);
insert into Membres (Nom, NomFamille, MembershipID) values ('Clayborne', 'McGreal', 19);
insert into Membres (Nom, NomFamille, MembershipID) values ('Cinderella', 'Alderson', 20);
insert into Membres (Nom, NomFamille, MembershipID) values ('Dael', 'Valintine', 21);
insert into Membres (Nom, NomFamille, MembershipID) values ('Lemuel', 'Guirardin', 22);
insert into Membres (Nom, NomFamille, MembershipID) values ('Bartram', 'Lattin', 23);
insert into Membres (Nom, NomFamille, MembershipID) values ('Aggi', 'Rignall', 24);
insert into Membres (Nom, NomFamille, MembershipID) values ('Sharlene', 'Moores', 25);
insert into Membres (Nom, NomFamille, MembershipID) values ('Jenelle', 'Semour', 26);
insert into Membres (Nom, NomFamille, MembershipID) values ('Bernetta', 'Nursey', 27);
insert into Membres (Nom, NomFamille, MembershipID) values ('Gertrud', 'Fosserd', 28);
insert into Membres (Nom, NomFamille, MembershipID) values ('Peggie', 'Stares', 29);
insert into Membres (Nom, NomFamille, MembershipID) values ('Donelle', 'Crommett', 30);
insert into Membres (Nom, NomFamille, MembershipID) values ('Darci', 'Brennenstuhl', 31);
insert into Membres (Nom, NomFamille, MembershipID) values ('Jeannette', 'Wilshaw', 32);
insert into Membres (Nom, NomFamille, MembershipID) values ('Merrielle', 'McOmish', 33);
insert into Membres (Nom, NomFamille, MembershipID) values ('Wallace', 'Tetsall', 34);
insert into Membres (Nom, NomFamille, MembershipID) values ('Mattheus', 'Grint', 35);
insert into Membres (Nom, NomFamille, MembershipID) values ('Paco', 'Jeste', 36);
insert into Membres (Nom, NomFamille, MembershipID) values ('Jada', 'Tomaszczyk', 37);
insert into Membres (Nom, NomFamille, MembershipID) values ('Kippar', 'McQuarter', 38);
insert into Membres (Nom, NomFamille, MembershipID) values ('Eleni', 'Cammocke', 39);
insert into Membres (Nom, NomFamille, MembershipID) values ('Aile', 'Boyfield', 40);
insert into Membres (Nom, NomFamille, MembershipID) values ('Meghann', 'Marlin', 41);
insert into Membres (Nom, NomFamille, MembershipID) values ('Harrietta', 'Dene', 42);
insert into Membres (Nom, NomFamille, MembershipID) values ('Thatcher', 'Spire', 43);
insert into Membres (Nom, NomFamille, MembershipID) values ('Charline', 'Cavanagh', 44);
insert into Membres (Nom, NomFamille, MembershipID) values ('Opaline', 'Maben', 45);
insert into Membres (Nom, NomFamille, MembershipID) values ('Roman', 'Paszak', 46);
insert into Membres (Nom, NomFamille, MembershipID) values ('Adda', 'Janaway', 47);
insert into Membres (Nom, NomFamille, MembershipID) values ('Seamus', 'Goldthorpe', 48);
insert into Membres (Nom, NomFamille, MembershipID) values ('Gustavo', 'Winfield', 49);
insert into Membres (Nom, NomFamille, MembershipID) values ('Stacee', 'Dench', 50);
insert into Membres (Nom, NomFamille, MembershipID) values ('Paten', 'Riggeard', 51);
insert into Membres (Nom, NomFamille, MembershipID) values ('Sullivan', 'Reeman', 52);
insert into Membres (Nom, NomFamille, MembershipID) values ('Gnni', 'Bickle', 53);
insert into Membres (Nom, NomFamille, MembershipID) values ('Daisey', 'Haack', 54);
insert into Membres (Nom, NomFamille, MembershipID) values ('Jaquenette', 'Chapman', 55);
insert into Membres (Nom, NomFamille, MembershipID) values ('Alwyn', 'Covely', 56);
insert into Membres (Nom, NomFamille, MembershipID) values ('Tonya', 'Tomini', 57);
insert into Membres (Nom, NomFamille, MembershipID) values ('Misha', 'Abade', 58);
insert into Membres (Nom, NomFamille, MembershipID) values ('Estele', 'Lawerence', 59);
insert into Membres (Nom, NomFamille, MembershipID) values ('Reece', 'Band', 60);
insert into Membres (Nom, NomFamille, MembershipID) values ('Archibaldo', 'Glasebrook', 61);
insert into Membres (Nom, NomFamille, MembershipID) values ('Guillema', 'Mandy', 62);
insert into Membres (Nom, NomFamille, MembershipID) values ('Casey', 'Sparrow', 63);
insert into Membres (Nom, NomFamille, MembershipID) values ('Benn', 'Fenty', 64);
insert into Membres (Nom, NomFamille, MembershipID) values ('Cindra', 'Posvner', 65);
insert into Membres (Nom, NomFamille, MembershipID) values ('Carolyne', 'Kraut', 66);
insert into Membres (Nom, NomFamille, MembershipID) values ('Lillian', 'Crockley', 67);
insert into Membres (Nom, NomFamille, MembershipID) values ('Eleonora', 'Aslet', 68);
insert into Membres (Nom, NomFamille, MembershipID) values ('Rikki', 'Pendred', 69);
insert into Membres (Nom, NomFamille, MembershipID) values ('Jenda', 'Paxman', 70);
insert into Membres (Nom, NomFamille, MembershipID) values ('Pincas', 'Spenceley', 71);
insert into Membres (Nom, NomFamille, MembershipID) values ('Nancy', 'Mewett', 72);
insert into Membres (Nom, NomFamille, MembershipID) values ('Teresa', 'Powlett', 73);
insert into Membres (Nom, NomFamille, MembershipID) values ('Albertine', 'Skelton', 74);
insert into Membres (Nom, NomFamille, MembershipID) values ('Valli', 'Feedome', 75);
insert into Membres (Nom, NomFamille, MembershipID) values ('Lari', 'Buckberry', 76);
insert into Membres (Nom, NomFamille, MembershipID) values ('Brittaney', 'Marousek', 77);
insert into Membres (Nom, NomFamille, MembershipID) values ('Horton', 'Cullabine', 78);
insert into Membres (Nom, NomFamille, MembershipID) values ('Renell', 'Braznell', 79);
insert into Membres (Nom, NomFamille, MembershipID) values ('Wilma', 'Glenister', 80);
insert into Membres (Nom, NomFamille, MembershipID) values ('Basia', 'Annott', 81);
insert into Membres (Nom, NomFamille, MembershipID) values ('Bruis', 'Durn', 82);
insert into Membres (Nom, NomFamille, MembershipID) values ('Tyson', 'Totton', 83);
insert into Membres (Nom, NomFamille, MembershipID) values ('Pauly', 'Lynas', 84);
insert into Membres (Nom, NomFamille, MembershipID) values ('Edna', 'Arnison', 85);
insert into Membres (Nom, NomFamille, MembershipID) values ('Joete', 'Speeks', 86);
insert into Membres (Nom, NomFamille, MembershipID) values ('Drusilla', 'Mowsdale', 87);
insert into Membres (Nom, NomFamille, MembershipID) values ('Aliza', 'Dumbleton', 88);
insert into Membres (Nom, NomFamille, MembershipID) values ('Galina', 'Dimeloe', 89);
insert into Membres (Nom, NomFamille, MembershipID) values ('Hube', 'Tale', 90);
insert into Membres (Nom, NomFamille, MembershipID) values ('Shamus', 'Raymen', 91);
insert into Membres (Nom, NomFamille, MembershipID) values ('Mozes', 'MacPhee', 92);
insert into Membres (Nom, NomFamille, MembershipID) values ('Ole', 'Tidball', 93);
insert into Membres (Nom, NomFamille, MembershipID) values ('Madlin', 'Chavey', 94);
insert into Membres (Nom, NomFamille, MembershipID) values ('Harriet', 'MacMearty', 95);
insert into Membres (Nom, NomFamille, MembershipID) values ('Elva', 'Cescotti', 96);
insert into Membres (Nom, NomFamille, MembershipID) values ('Becca', 'Ridder', 97);
insert into Membres (Nom, NomFamille, MembershipID) values ('Verney', 'Prosch', 98);
insert into Membres (Nom, NomFamille, MembershipID) values ('Skipp', 'Trelease', 99);
insert into Membres (Nom, NomFamille, MembershipID) values ('Mariska', 'Karim', 100);
insert into Membres (Nom, NomFamille, MembershipID) values ('Dina', 'Lechmere', 101);
insert into Membres (Nom, NomFamille, MembershipID) values ('Jeremy', 'Willavize', 102);
insert into Membres (Nom, NomFamille, MembershipID) values ('Peria', 'Van Velde', 103);
insert into Membres (Nom, NomFamille, MembershipID) values ('Dilly', 'MacCaig', 104);
insert into Membres (Nom, NomFamille, MembershipID) values ('Matilda', 'Bedenham', 105);
insert into Membres (Nom, NomFamille, MembershipID) values ('Sutherlan', 'Lind', 106);
insert into Membres (Nom, NomFamille, MembershipID) values ('Kingsly', 'Weeks', 107);
insert into Membres (Nom, NomFamille, MembershipID) values ('Windham', 'Harcombe', 108);
insert into Membres (Nom, NomFamille, MembershipID) values ('Maxi', 'Vasyanin', 109);
insert into Membres (Nom, NomFamille, MembershipID) values ('Jobi', 'Bonifas', 110);
insert into Membres (Nom, NomFamille, MembershipID) values ('Manny', 'Stagge', 111);
insert into Membres (Nom, NomFamille, MembershipID) values ('Ami', 'Bartosek', 112);
insert into Membres (Nom, NomFamille, MembershipID) values ('Neda', 'Symon', 113);
insert into Membres (Nom, NomFamille, MembershipID) values ('Emmi', 'Cowpland', 114);
insert into Membres (Nom, NomFamille, MembershipID) values ('Jammal', 'Josef', 115);
insert into Membres (Nom, NomFamille, MembershipID) values ('Porter', 'Merryweather', 116);
insert into Membres (Nom, NomFamille, MembershipID) values ('Darn', 'O'' Gara', 117);
insert into Membres (Nom, NomFamille, MembershipID) values ('Brita', 'Burris', 118);
insert into Membres (Nom, NomFamille, MembershipID) values ('Burt', 'Iapico', 119);
insert into Membres (Nom, NomFamille, MembershipID) values ('Marie-ann', 'Navarro', 120);
insert into Membres (Nom, NomFamille, MembershipID) values ('Valdemar', 'Matterdace', 121);
insert into Membres (Nom, NomFamille, MembershipID) values ('Doug', 'Hawtin', 122);
insert into Membres (Nom, NomFamille, MembershipID) values ('Odelle', 'Effnert', 123);
insert into Membres (Nom, NomFamille, MembershipID) values ('Logan', 'Heymann', 124);
insert into Membres (Nom, NomFamille, MembershipID) values ('Wynne', 'Trustrie', 125);
insert into Membres (Nom, NomFamille, MembershipID) values ('Deni', 'Volker', 126);
insert into Membres (Nom, NomFamille, MembershipID) values ('Jo-ann', 'Pert', 127);
insert into Membres (Nom, NomFamille, MembershipID) values ('Howey', 'Eyer', 128);
insert into Membres (Nom, NomFamille, MembershipID) values ('Gilberta', 'Marke', 129);
insert into Membres (Nom, NomFamille, MembershipID) values ('Broderic', 'Cockson', 130);
insert into Membres (Nom, NomFamille, MembershipID) values ('Guinna', 'Liddy', 131);
insert into Membres (Nom, NomFamille, MembershipID) values ('Standford', 'Gradwell', 132);
insert into Membres (Nom, NomFamille, MembershipID) values ('Sayres', 'Dutnell', 133);
insert into Membres (Nom, NomFamille, MembershipID) values ('Dolley', 'Kavanagh', 134);
insert into Membres (Nom, NomFamille, MembershipID) values ('Axe', 'Isles', 135);
insert into Membres (Nom, NomFamille, MembershipID) values ('Ola', 'Nardrup', 136);
insert into Membres (Nom, NomFamille, MembershipID) values ('Barret', 'Geaney', 137);
insert into Membres (Nom, NomFamille, MembershipID) values ('Royall', 'Janisson', 138);
insert into Membres (Nom, NomFamille, MembershipID) values ('Dud', 'Brixey', 139);
insert into Membres (Nom, NomFamille, MembershipID) values ('Mufinella', 'Itzig', 140);
insert into Membres (Nom, NomFamille, MembershipID) values ('Max', 'Chipp', 141);
insert into Membres (Nom, NomFamille, MembershipID) values ('Merill', 'Vergine', 142);
insert into Membres (Nom, NomFamille, MembershipID) values ('Mahmoud', 'Simonassi', 143);
insert into Membres (Nom, NomFamille, MembershipID) values ('Elias', 'Croose', 144);
insert into Membres (Nom, NomFamille, MembershipID) values ('Adriano', 'Karpmann', 145);
insert into Membres (Nom, NomFamille, MembershipID) values ('Ardath', 'Dorton', 146);
insert into Membres (Nom, NomFamille, MembershipID) values ('Gherardo', 'Snozzwell', 147);
insert into Membres (Nom, NomFamille, MembershipID) values ('Pincus', 'Le Batteur', 148);
insert into Membres (Nom, NomFamille, MembershipID) values ('Dulci', 'Kapelhoff', 149);
insert into Membres (Nom, NomFamille, MembershipID) values ('Rhys', 'Laundon', 150);
insert into Membres (Nom, NomFamille, MembershipID) values ('Cass', 'Elcom', 151);
insert into Membres (Nom, NomFamille, MembershipID) values ('Orran', 'Pothergill', 152);
insert into Membres (Nom, NomFamille, MembershipID) values ('Raoul', 'Pirot', 153);
insert into Membres (Nom, NomFamille, MembershipID) values ('Bari', 'Roggerone', 154);
insert into Membres (Nom, NomFamille, MembershipID) values ('Salem', 'Habard', 155);
insert into Membres (Nom, NomFamille, MembershipID) values ('Renelle', 'Douberday', 156);
insert into Membres (Nom, NomFamille, MembershipID) values ('Dannye', 'Deville', 157);
insert into Membres (Nom, NomFamille, MembershipID) values ('Saidee', 'Ferrers', 158);
insert into Membres (Nom, NomFamille, MembershipID) values ('Julee', 'Milne', 159);
insert into Membres (Nom, NomFamille, MembershipID) values ('Fawne', 'Demann', 160);
insert into Membres (Nom, NomFamille, MembershipID) values ('Karleen', 'Braycotton', 161);
insert into Membres (Nom, NomFamille, MembershipID) values ('Colby', 'Carwardine', 162);
insert into Membres (Nom, NomFamille, MembershipID) values ('Granville', 'Milland', 163);
insert into Membres (Nom, NomFamille, MembershipID) values ('Dulcy', 'Keer', 164);
insert into Membres (Nom, NomFamille, MembershipID) values ('Jehu', 'Hansman', 165);
insert into Membres (Nom, NomFamille, MembershipID) values ('Thalia', 'Lead', 166);
insert into Membres (Nom, NomFamille, MembershipID) values ('Joletta', 'Olifard', 167);
insert into Membres (Nom, NomFamille, MembershipID) values ('Pietra', 'Trubshaw', 168);
insert into Membres (Nom, NomFamille, MembershipID) values ('Koenraad', 'Tondeur', 169);
insert into Membres (Nom, NomFamille, MembershipID) values ('Rockey', 'Sprowson', 170);
insert into Membres (Nom, NomFamille, MembershipID) values ('Tades', 'Sudell', 171);
insert into Membres (Nom, NomFamille, MembershipID) values ('Carmina', 'Chesshire', 172);
insert into Membres (Nom, NomFamille, MembershipID) values ('Ulberto', 'Kingzet', 173);
insert into Membres (Nom, NomFamille, MembershipID) values ('Ulysses', 'Pillinger', 174);
insert into Membres (Nom, NomFamille, MembershipID) values ('Theodor', 'Merkel', 175);
insert into Membres (Nom, NomFamille, MembershipID) values ('Gweneth', 'Goulbourn', 176);
insert into Membres (Nom, NomFamille, MembershipID) values ('Brock', 'Philippart', 177);
insert into Membres (Nom, NomFamille, MembershipID) values ('Fleming', 'McDonald', 178);
insert into Membres (Nom, NomFamille, MembershipID) values ('Uriah', 'Middas', 179);
insert into Membres (Nom, NomFamille, MembershipID) values ('Angil', 'Walesby', 180);
insert into Membres (Nom, NomFamille, MembershipID) values ('Alessandro', 'Mateus', 181);
insert into Membres (Nom, NomFamille, MembershipID) values ('Jose', 'Reyburn', 182);
insert into Membres (Nom, NomFamille, MembershipID) values ('Meridith', 'Bolliver', 183);
insert into Membres (Nom, NomFamille, MembershipID) values ('Munroe', 'Croci', 184);
insert into Membres (Nom, NomFamille, MembershipID) values ('Bernarr', 'O''Sherrin', 185);
insert into Membres (Nom, NomFamille, MembershipID) values ('Zita', 'Tidridge', 186);
insert into Membres (Nom, NomFamille, MembershipID) values ('Adair', 'Dixcee', 187);
insert into Membres (Nom, NomFamille, MembershipID) values ('Inga', 'Ritmeyer', 188);
insert into Membres (Nom, NomFamille, MembershipID) values ('Munroe', 'McFeate', 189);
insert into Membres (Nom, NomFamille, MembershipID) values ('Gennifer', 'Killick', 190);
insert into Membres (Nom, NomFamille, MembershipID) values ('Ed', 'Habens', 191);
insert into Membres (Nom, NomFamille, MembershipID) values ('Riccardo', 'Dymocke', 192);
insert into Membres (Nom, NomFamille, MembershipID) values ('Talbert', 'Woolham', 193);
insert into Membres (Nom, NomFamille, MembershipID) values ('Joscelin', 'Feek', 194);
insert into Membres (Nom, NomFamille, MembershipID) values ('Carlina', 'Hull', 195);
insert into Membres (Nom, NomFamille, MembershipID) values ('Alie', 'Zimmermanns', 196);
insert into Membres (Nom, NomFamille, MembershipID) values ('Whitman', 'Mix', 197);
insert into Membres (Nom, NomFamille, MembershipID) values ('Dorisa', 'Marrian', 198);
insert into Membres (Nom, NomFamille, MembershipID) values ('Brewer', 'Cottie', 199);
insert into Membres (Nom, NomFamille, MembershipID) values ('Jillian', 'Sawford', 200);
insert into Membres (Nom, NomFamille, MembershipID) values ('Laurette', 'Goodnow', 201);
insert into Membres (Nom, NomFamille, MembershipID) values ('Lief', 'Lees', 202);
insert into Membres (Nom, NomFamille, MembershipID) values ('Darb', 'Cristoferi', 203);
insert into Membres (Nom, NomFamille, MembershipID) values ('Dalia', 'Ziemsen', 204);
insert into Membres (Nom, NomFamille, MembershipID) values ('Callie', 'Habishaw', 205);
insert into Membres (Nom, NomFamille, MembershipID) values ('Lisle', 'Trunks', 206);
insert into Membres (Nom, NomFamille, MembershipID) values ('Elli', 'Toomer', 207);
insert into Membres (Nom, NomFamille, MembershipID) values ('Rodina', 'Godlee', 208);
insert into Membres (Nom, NomFamille, MembershipID) values ('Windy', 'Winfindine', 209);
insert into Membres (Nom, NomFamille, MembershipID) values ('Waite', 'Baxill', 210);
insert into Membres (Nom, NomFamille, MembershipID) values ('Clarita', 'Sanpher', 211);
insert into Membres (Nom, NomFamille, MembershipID) values ('Budd', 'Tomlins', 212);
insert into Membres (Nom, NomFamille, MembershipID) values ('Milli', 'Burdytt', 213);
insert into Membres (Nom, NomFamille, MembershipID) values ('Manuel', 'Petley', 214);
insert into Membres (Nom, NomFamille, MembershipID) values ('Else', 'Thiese', 215);
insert into Membres (Nom, NomFamille, MembershipID) values ('Colene', 'Ruegg', 216);
insert into Membres (Nom, NomFamille, MembershipID) values ('Crichton', 'Tellesson', 217);
insert into Membres (Nom, NomFamille, MembershipID) values ('Jase', 'Husbands', 218);
insert into Membres (Nom, NomFamille, MembershipID) values ('Alane', 'Keningley', 219);
insert into Membres (Nom, NomFamille, MembershipID) values ('Adrien', 'Lauritsen', 220);
insert into Membres (Nom, NomFamille, MembershipID) values ('Cam', 'Twelvetrees', 221);
insert into Membres (Nom, NomFamille, MembershipID) values ('Winnifred', 'Torrent', 222);
insert into Membres (Nom, NomFamille, MembershipID) values ('Ber', 'Strode', 223);
insert into Membres (Nom, NomFamille, MembershipID) values ('Lilas', 'Clackers', 224);
insert into Membres (Nom, NomFamille, MembershipID) values ('Henryetta', 'Mayhou', 225);




--- donnée pour la table Entraineur ---
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Mathew', '11/24/1981', 4);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Aura', '10/21/1973', 10);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Nanice', '5/29/1971', 2);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Melvin', '10/31/1976', 6);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Kenyon', '10/10/2002', 3);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Jamaal', '10/25/2005', 1);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Chanda', '2/19/2005', 8);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Daffy', '7/12/1984', 6);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Aila', '5/14/1975', 7);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Starr', '9/2/1997', 3);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Caritta', '7/26/1984', 1);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Adore', '2/8/1997', 3);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Camel', '10/11/1982', 10);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Jewelle', '1/27/1981', 7);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Berni', '10/8/1995', 1);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Freddy', '2/22/2001', 9);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Lewiss', '8/17/1979', 2);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Seward', '10/7/1985', 5);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Udale', '9/29/1988', 7);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Giffer', '7/20/1981', 5);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Jenilee', '6/7/1990', 5);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Frasco', '6/24/1991', 9);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Heda', '9/14/2004', 6);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Bella', '1/26/2003', 6);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Cyb', '11/26/1970', 7);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Gustavo', '12/7/1998', 9);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Bernadine', '12/10/1976', 3);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Prentice', '6/12/1995', 7);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Adda', '9/15/1978', 6);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Nadia', '3/29/2004', 10);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Shandra', '9/13/2004', 5);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Ashly', '11/24/1970', 4);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Alta', '4/9/1992', 6);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Nikolos', '4/27/1972', 7);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Sadie', '10/13/2007', 9);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Ursa', '9/8/2000', 8);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Marjie', '1/22/1974', 10);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Horst', '12/7/1976', 5);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Dagmar', '7/1/2006', 3);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Petronille', '8/2/1974', 5);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Godiva', '3/31/1981', 6);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Mignon', '5/21/1988', 7);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Loralie', '2/8/1998', 10);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Cathlene', '12/26/1971', 6);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Brook', '5/10/1998', 9);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Wrennie', '3/29/1979', 1);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Dev', '7/11/1993', 8);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Frasquito', '10/13/2005', 4);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Gideon', '10/26/1976', 3);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Hanson', '11/2/1996', 3);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Broddy', '7/2/1986', 8);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Keith', '5/19/1997', 2);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Arri', '7/27/2007', 8);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Cathrin', '7/26/2002', 7);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Dahlia', '1/27/2001', 3);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Aindrea', '3/8/1973', 1);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Bartolomeo', '5/25/1978', 5);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Tally', '5/1/1977', 2);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Martina', '9/7/1994', 8);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Quinton', '1/10/1986', 8);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Celene', '10/26/2001', 5);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Corry', '12/20/1981', 5);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Lorne', '6/28/1989', 1);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Roderigo', '11/9/1994', 5);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Clarice', '2/26/1996', 10);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Cassey', '1/1/1996', 1);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Adolf', '2/2/1982', 6);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Adam', '9/28/1988', 1);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Gustavus', '6/2/1996', 2);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Blanch', '7/9/2003', 1);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Sonia', '12/26/1990', 10);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Thatcher', '5/16/1998', 10);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Dewey', '6/16/1976', 9);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Nadeen', '7/8/1988', 1);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Dodie', '11/30/1997', 6);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Gonzales', '11/1/1993', 2);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Carilyn', '1/28/2003', 10);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Munroe', '1/16/1988', 3);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Oneida', '2/20/1991', 10);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Gustie', '6/26/1990', 5);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Brnaba', '10/16/1993', 3);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Yvonne', '3/11/1973', 9);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Donnell', '9/25/1987', 2);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Gavan', '4/15/1984', 9);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Eleanora', '11/12/2001', 5);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Carilyn', '8/27/1998', 1);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Everard', '2/11/1979', 5);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Irena', '9/23/2002', 4);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Maris', '8/14/1992', 8);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Codi', '5/29/1984', 3);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Gannon', '2/26/1980', 10);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Blanca', '4/29/1995', 7);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Imogen', '3/2/2007', 9);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Aprilette', '3/4/1977', 5);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Brad', '10/13/1991', 9);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Gard', '5/8/1993', 1);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Pepito', '9/17/1983', 1);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Bartolomeo', '11/28/1991', 4);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Nolly', '10/23/2000', 3);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Thorndike', '5/25/2005', 2);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Lenora', '11/22/1979', 6);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Karoly', '7/5/1991', 10);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Simone', '11/1/2006', 10);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Hildagarde', '3/10/1977', 2);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Delila', '2/10/1972', 7);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Linoel', '8/8/1977', 4);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Leonora', '3/21/1982', 4);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Neila', '9/9/1985', 3);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Cazzie', '1/2/1975', 5);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Beitris', '12/14/2002', 2);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Aretha', '12/24/1989', 2);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Yorke', '11/13/1987', 5);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Nathalie', '5/12/1983', 5);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Arleta', '7/19/1993', 8);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Nye', '12/30/2003', 3);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Isabel', '9/28/2005', 6);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Darda', '7/21/1979', 7);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Leanora', '7/18/1991', 4);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Roosevelt', '11/19/1983', 8);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Dav', '4/3/1988', 5);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Tonie', '12/26/1998', 8);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Shanie', '8/9/1978', 1);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Rochester', '1/4/1999', 7);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Cybill', '5/10/1971', 5);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Renae', '3/2/1997', 8);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Darice', '6/16/2000', 7);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Gothart', '7/8/1972', 2);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Gerda', '7/31/2004', 7);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Loren', '6/9/2003', 3);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Korney', '9/15/1990', 1);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Dreddy', '12/3/1994', 8);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Meridel', '9/18/1977', 5);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Noble', '10/26/1972', 1);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Alyosha', '1/13/1977', 3);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Phillipp', '4/28/1987', 6);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Steve', '10/14/2001', 7);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Opal', '4/22/2000', 5);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Alasdair', '12/6/1976', 9);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Marvin', '11/17/1991', 3);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Jany', '7/11/1990', 8);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Filmore', '11/17/1998', 1);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Konrad', '9/5/1992', 9);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Annadiane', '2/12/1978', 1);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Far', '12/27/2003', 4);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Rozamond', '6/7/1988', 1);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Olivier', '5/28/2004', 1);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Tadd', '10/9/1998', 3);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Rolando', '11/26/1993', 4);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Wilona', '12/11/1999', 5);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Cart', '10/12/2006', 5);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Damon', '4/28/1987', 5);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Melvyn', '9/18/1972', 9);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Brice', '10/9/1978', 1);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Willey', '8/14/1999', 3);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Georas', '1/5/1980', 9);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Conny', '11/23/2002', 9);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Ediva', '3/18/1973', 4);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Iseabal', '7/24/2002', 3);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Vassili', '3/4/2000', 4);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Delmor', '3/6/1981', 8);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Meredith', '12/29/1986', 1);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Kordula', '10/19/1997', 4);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Bradan', '3/14/1979', 1);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Dieter', '8/11/1997', 10);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Noel', '7/10/2004', 8);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Elmore', '2/1/1971', 1);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Miguela', '12/18/1992', 3);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Carny', '4/3/1974', 10);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Mohammed', '9/21/1982', 9);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Shurwood', '3/15/1996', 8);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Emmet', '10/11/1986', 10);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Stanton', '4/12/1986', 8);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Bord', '3/2/1974', 4);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Mia', '3/8/1992', 1);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Eula', '10/23/1973', 8);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Cecelia', '7/10/1986', 4);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Patin', '8/18/2000', 2);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Rodi', '9/21/1986', 4);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Shel', '9/28/1993', 8);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Templeton', '1/6/1988', 5);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Coretta', '1/7/1978', 5);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Mathias', '12/24/1984', 10);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Brena', '5/27/1992', 2);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Quillan', '9/16/1976', 8);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Cristy', '5/19/1991', 4);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Fleurette', '3/4/1973', 4);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Wallis', '2/14/1991', 2);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Ciro', '8/20/1984', 5);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Hieronymus', '1/5/1978', 6);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Jemima', '1/31/1980', 3);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Adorne', '2/7/1994', 4);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Arnuad', '8/1/1974', 2);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Alfy', '4/16/1979', 3);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Carey', '9/4/1987', 6);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Bren', '1/18/1990', 2);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Hymie', '2/19/1972', 6);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Kittie', '11/29/1998', 9);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Paco', '10/17/1971', 9);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Kienan', '5/24/1983', 3);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Renate', '5/20/1988', 4);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Wald', '3/17/1978', 6);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Kylie', '3/2/2006', 6);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Kara-lynn', '10/8/1993', 7);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Adi', '6/11/1995', 5);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Ava', '3/13/1989', 1);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Vance', '7/22/1997', 5);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Ferd', '6/29/2002', 2);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Delora', '7/3/1982', 9);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Delilah', '12/6/1999', 1);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Ewart', '3/11/1998', 6);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Reinwald', '12/12/1979', 6);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('De witt', '3/7/2003', 8);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Basil', '8/6/1994', 6);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Raf', '1/28/1975', 9);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Cole', '1/12/1974', 5);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Dougy', '10/17/1984', 5);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Rick', '10/25/2006', 10);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Katherina', '5/29/2004', 3);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Magdaia', '2/11/1983', 10);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Graeme', '8/10/1972', 8);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Mehetabel', '2/14/2002', 2);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Kiele', '2/6/1987', 2);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Chadd', '2/2/1989', 6);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Del', '9/20/1994', 2);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Alyssa', '8/15/1986', 6);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Bernetta', '3/15/2007', 5);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Perceval', '5/12/1981', 8);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Frances', '9/6/2003', 1);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Clari', '1/13/1996', 2);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Ron', '7/16/1979', 2);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Romain', '2/13/2001', 4);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Romonda', '11/29/1972', 5);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Layne', '1/9/1981', 9);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Carry', '8/25/1990', 3);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Louisette', '12/25/2006', 4);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Lorine', '9/6/1999', 1);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Camille', '7/29/2004', 8);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Kalil', '12/24/1997', 8);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Florinda', '2/25/1992', 2);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Ruddie', '3/25/1986', 10);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Ashly', '6/21/1974', 10);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Lucio', '2/14/1979', 5);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Sylvia', '6/30/1996', 2);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Darline', '9/22/1988', 9);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Sollie', '10/11/2007', 7);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Cassandre', '5/15/1998', 7);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Joel', '12/17/1982', 2);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Reginald', '12/21/1974', 1);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Hadleigh', '10/29/1984', 3);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Celinda', '4/4/2006', 2);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Gertrud', '9/29/2004', 7);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Damaris', '10/15/1981', 1);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Evangelina', '12/6/1992', 2);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Nertie', '7/19/2005', 3);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Rodge', '6/2/2000', 4);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Lucilia', '2/17/1991', 9);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Norri', '9/10/1991', 3);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Elka', '4/2/1983', 4);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Willard', '8/9/1978', 5);
insert into Entraineur (Nom, DateNais, Niveau_Expérience) values ('Maritsa', '1/10/1994', 6);



--- Donée pour Cours --
insert into Cours (NomDeCours, TempsCours) values ('cardio', '7:32 PM');
insert into Cours (NomDeCours, TempsCours) values ('cardio', '10:11 AM');
insert into Cours (NomDeCours, TempsCours) values ('cardio', '7:49 AM');
insert into Cours (NomDeCours, TempsCours) values ('gym', '1:04 PM');
insert into Cours (NomDeCours, TempsCours) values ('gym', '4:37 PM');
insert into Cours (NomDeCours, TempsCours) values ('cardio', '6:20 PM');
insert into Cours (NomDeCours, TempsCours) values ('cardio', '6:51 AM');
insert into Cours (NomDeCours, TempsCours) values ('cardio', '7:55 PM');
insert into Cours (NomDeCours, TempsCours) values ('gym', '10:51 AM');
insert into Cours (NomDeCours, TempsCours) values ('cardio', '6:45 AM');
insert into Cours (NomDeCours, TempsCours) values ('crossfit', '10:05 AM');
insert into Cours (NomDeCours, TempsCours) values ('gym', '2:51 PM');
insert into Cours (NomDeCours, TempsCours) values ('gym', '10:17 AM');
insert into Cours (NomDeCours, TempsCours) values ('crossfit', '7:21 PM');
insert into Cours (NomDeCours, TempsCours) values ('gym', '1:08 PM');
insert into Cours (NomDeCours, TempsCours) values ('crossfit', '5:18 PM');
insert into Cours (NomDeCours, TempsCours) values ('gym', '9:48 AM');
insert into Cours (NomDeCours, TempsCours) values ('gym', '8:56 AM');
insert into Cours (NomDeCours, TempsCours) values ('crossfit', '12:18 PM');
insert into Cours (NomDeCours, TempsCours) values ('gym', '7:41 PM');
insert into Cours (NomDeCours, TempsCours) values ('cardio', '9:47 AM');
insert into Cours (NomDeCours, TempsCours) values ('crossfit', '7:04 AM');
insert into Cours (NomDeCours, TempsCours) values ('crossfit', '4:22 PM');
insert into Cours (NomDeCours, TempsCours) values ('crossfit', '4:29 PM');
insert into Cours (NomDeCours, TempsCours) values ('gym', '3:15 PM');
insert into Cours (NomDeCours, TempsCours) values ('gym', '12:51 PM');
insert into Cours (NomDeCours, TempsCours) values ('crossfit', '3:07 PM');
insert into Cours (NomDeCours, TempsCours) values ('cardio', '7:08 AM');
insert into Cours (NomDeCours, TempsCours) values ('cardio', '6:32 PM');
insert into Cours (NomDeCours, TempsCours) values ('cardio', '6:59 PM');
insert into Cours (NomDeCours, TempsCours) values ('cardio', '10:07 AM');
insert into Cours (NomDeCours, TempsCours) values ('crossfit', '5:55 PM');
insert into Cours (NomDeCours, TempsCours) values ('cardio', '5:05 PM');
insert into Cours (NomDeCours, TempsCours) values ('crossfit', '7:38 AM');
insert into Cours (NomDeCours, TempsCours) values ('gym', '12:43 PM');
insert into Cours (NomDeCours, TempsCours) values ('crossfit', '7:32 PM');
insert into Cours (NomDeCours, TempsCours) values ('crossfit', '11:00 AM');
insert into Cours (NomDeCours, TempsCours) values ('gym', '3:03 PM');
insert into Cours (NomDeCours, TempsCours) values ('gym', '3:32 PM');
insert into Cours (NomDeCours, TempsCours) values ('crossfit', '5:57 PM');
insert into Cours (NomDeCours, TempsCours) values ('crossfit', '11:56 AM');
insert into Cours (NomDeCours, TempsCours) values ('crossfit', '7:17 PM');
insert into Cours (NomDeCours, TempsCours) values ('cardio', '7:45 PM');
insert into Cours (NomDeCours, TempsCours) values ('crossfit', '1:01 PM');
insert into Cours (NomDeCours, TempsCours) values ('gym', '12:29 PM');
insert into Cours (NomDeCours, TempsCours) values ('cardio', '6:01 PM');
insert into Cours (NomDeCours, TempsCours) values ('cardio', '2:13 PM');
insert into Cours (NomDeCours, TempsCours) values ('gym', '6:05 AM');
insert into Cours (NomDeCours, TempsCours) values ('crossfit', '8:13 AM');
insert into Cours (NomDeCours, TempsCours) values ('cardio', '2:57 PM');
insert into Cours (NomDeCours, TempsCours) values ('gym', '11:25 AM');
insert into Cours (NomDeCours, TempsCours) values ('crossfit', '7:50 AM');
insert into Cours (NomDeCours, TempsCours) values ('gym', '1:26 PM');
insert into Cours (NomDeCours, TempsCours) values ('cardio', '12:32 PM');
insert into Cours (NomDeCours, TempsCours) values ('gym', '6:09 PM');
insert into Cours (NomDeCours, TempsCours) values ('cardio', '10:19 AM');
insert into Cours (NomDeCours, TempsCours) values ('cardio', '6:00 PM');
insert into Cours (NomDeCours, TempsCours) values ('gym', '7:56 PM');
insert into Cours (NomDeCours, TempsCours) values ('crossfit', '7:36 AM');
insert into Cours (NomDeCours, TempsCours) values ('cardio', '7:33 PM');
insert into Cours (NomDeCours, TempsCours) values ('gym', '1:27 PM');
insert into Cours (NomDeCours, TempsCours) values ('cardio', '8:47 AM');
insert into Cours (NomDeCours, TempsCours) values ('gym', '2:27 PM');
insert into Cours (NomDeCours, TempsCours) values ('gym', '5:03 PM');
insert into Cours (NomDeCours, TempsCours) values ('gym', '6:56 PM');
insert into Cours (NomDeCours, TempsCours) values ('gym', '9:16 AM');
insert into Cours (NomDeCours, TempsCours) values ('cardio', '12:16 PM');
insert into Cours (NomDeCours, TempsCours) values ('crossfit', '8:35 AM');
insert into Cours (NomDeCours, TempsCours) values ('cardio', '6:37 PM');
insert into Cours (NomDeCours, TempsCours) values ('cardio', '6:55 PM');
insert into Cours (NomDeCours, TempsCours) values ('gym', '4:22 PM');
insert into Cours (NomDeCours, TempsCours) values ('crossfit', '7:28 PM');
insert into Cours (NomDeCours, TempsCours) values ('cardio', '7:52 PM');
insert into Cours (NomDeCours, TempsCours) values ('gym', '11:48 AM');
insert into Cours (NomDeCours, TempsCours) values ('crossfit', '2:25 PM');
insert into Cours (NomDeCours, TempsCours) values ('gym', '11:41 AM');
insert into Cours (NomDeCours, TempsCours) values ('crossfit', '1:30 PM');
insert into Cours (NomDeCours, TempsCours) values ('gym', '2:28 PM');
insert into Cours (NomDeCours, TempsCours) values ('crossfit', '11:35 AM');
insert into Cours (NomDeCours, TempsCours) values ('crossfit', '6:14 PM');
insert into Cours (NomDeCours, TempsCours) values ('cardio', '7:34 PM');
insert into Cours (NomDeCours, TempsCours) values ('gym', '7:23 AM');
insert into Cours (NomDeCours, TempsCours) values ('cardio', '9:06 AM');
insert into Cours (NomDeCours, TempsCours) values ('crossfit', '3:57 PM');
insert into Cours (NomDeCours, TempsCours) values ('cardio', '2:16 PM');
insert into Cours (NomDeCours, TempsCours) values ('crossfit', '9:15 AM');
insert into Cours (NomDeCours, TempsCours) values ('cardio', '2:51 PM');
insert into Cours (NomDeCours, TempsCours) values ('cardio', '5:32 PM');
insert into Cours (NomDeCours, TempsCours) values ('crossfit', '1:42 PM');
insert into Cours (NomDeCours, TempsCours) values ('gym', '7:18 AM');
insert into Cours (NomDeCours, TempsCours) values ('crossfit', '3:44 PM');
insert into Cours (NomDeCours, TempsCours) values ('gym', '3:40 PM');
insert into Cours (NomDeCours, TempsCours) values ('cardio', '6:53 AM');
insert into Cours (NomDeCours, TempsCours) values ('cardio', '10:19 AM');
insert into Cours (NomDeCours, TempsCours) values ('cardio', '9:13 AM');
insert into Cours (NomDeCours, TempsCours) values ('cardio', '5:06 PM');
insert into Cours (NomDeCours, TempsCours) values ('cardio', '8:06 AM');
insert into Cours (NomDeCours, TempsCours) values ('crossfit', '11:34 AM');
insert into Cours (NomDeCours, TempsCours) values ('crossfit', '10:55 AM');
insert into Cours (NomDeCours, TempsCours) values ('gym', '11:26 AM');
insert into Cours (NomDeCours, TempsCours) values ('gym', '7:53 AM');
insert into Cours (NomDeCours, TempsCours) values ('gym', '12:23 PM');
insert into Cours (NomDeCours, TempsCours) values ('cardio', '6:21 AM');
insert into Cours (NomDeCours, TempsCours) values ('crossfit', '11:22 AM');
insert into Cours (NomDeCours, TempsCours) values ('cardio', '7:22 AM');
insert into Cours (NomDeCours, TempsCours) values ('gym', '9:30 AM');
insert into Cours (NomDeCours, TempsCours) values ('cardio', '8:27 AM');
insert into Cours (NomDeCours, TempsCours) values ('crossfit', '4:22 PM');
insert into Cours (NomDeCours, TempsCours) values ('gym', '6:33 AM');
insert into Cours (NomDeCours, TempsCours) values ('crossfit', '4:11 PM');
insert into Cours (NomDeCours, TempsCours) values ('crossfit', '6:28 AM');
insert into Cours (NomDeCours, TempsCours) values ('crossfit', '6:57 PM');
insert into Cours (NomDeCours, TempsCours) values ('gym', '12:47 PM');
insert into Cours (NomDeCours, TempsCours) values ('gym', '6:52 PM');
insert into Cours (NomDeCours, TempsCours) values ('crossfit', '8:03 AM');
insert into Cours (NomDeCours, TempsCours) values ('gym', '7:03 PM');
insert into Cours (NomDeCours, TempsCours) values ('crossfit', '6:13 PM');
insert into Cours (NomDeCours, TempsCours) values ('crossfit', '5:17 PM');
insert into Cours (NomDeCours, TempsCours) values ('crossfit', '9:50 AM');
insert into Cours (NomDeCours, TempsCours) values ('crossfit', '4:45 PM');
insert into Cours (NomDeCours, TempsCours) values ('gym', '9:11 AM');
insert into Cours (NomDeCours, TempsCours) values ('gym', '2:14 PM');
insert into Cours (NomDeCours, TempsCours) values ('gym', '7:02 PM');
insert into Cours (NomDeCours, TempsCours) values ('gym', '9:37 AM');
insert into Cours (NomDeCours, TempsCours) values ('gym', '6:17 AM');
insert into Cours (NomDeCours, TempsCours) values ('gym', '3:49 PM');
insert into Cours (NomDeCours, TempsCours) values ('gym', '1:42 PM');
insert into Cours (NomDeCours, TempsCours) values ('gym', '7:45 AM');
insert into Cours (NomDeCours, TempsCours) values ('cardio', '5:22 PM');
insert into Cours (NomDeCours, TempsCours) values ('cardio', '6:30 AM');
insert into Cours (NomDeCours, TempsCours) values ('crossfit', '9:31 AM');
insert into Cours (NomDeCours, TempsCours) values ('gym', '7:32 PM');
insert into Cours (NomDeCours, TempsCours) values ('crossfit', '6:51 AM');
insert into Cours (NomDeCours, TempsCours) values ('cardio', '4:18 PM');
insert into Cours (NomDeCours, TempsCours) values ('crossfit', '12:55 PM');
insert into Cours (NomDeCours, TempsCours) values ('crossfit', '4:05 PM');
insert into Cours (NomDeCours, TempsCours) values ('crossfit', '6:31 PM');
insert into Cours (NomDeCours, TempsCours) values ('gym', '3:43 PM');
insert into Cours (NomDeCours, TempsCours) values ('cardio', '7:55 AM');
insert into Cours (NomDeCours, TempsCours) values ('gym', '8:52 AM');
insert into Cours (NomDeCours, TempsCours) values ('crossfit', '7:23 AM');
insert into Cours (NomDeCours, TempsCours) values ('gym', '1:35 PM');
insert into Cours (NomDeCours, TempsCours) values ('gym', '4:07 PM');
insert into Cours (NomDeCours, TempsCours) values ('gym', '1:13 PM');
insert into Cours (NomDeCours, TempsCours) values ('crossfit', '6:04 AM');
insert into Cours (NomDeCours, TempsCours) values ('cardio', '12:51 PM');
insert into Cours (NomDeCours, TempsCours) values ('crossfit', '4:10 PM');
insert into Cours (NomDeCours, TempsCours) values ('gym', '7:01 PM');
insert into Cours (NomDeCours, TempsCours) values ('cardio', '7:04 PM');
insert into Cours (NomDeCours, TempsCours) values ('crossfit', '6:50 AM');
insert into Cours (NomDeCours, TempsCours) values ('crossfit', '10:50 AM');
insert into Cours (NomDeCours, TempsCours) values ('cardio', '5:21 PM');
insert into Cours (NomDeCours, TempsCours) values ('gym', '7:40 AM');
insert into Cours (NomDeCours, TempsCours) values ('crossfit', '12:44 PM');
insert into Cours (NomDeCours, TempsCours) values ('crossfit', '9:46 AM');
insert into Cours (NomDeCours, TempsCours) values ('crossfit', '11:34 AM');
insert into Cours (NomDeCours, TempsCours) values ('gym', '7:25 AM');
insert into Cours (NomDeCours, TempsCours) values ('crossfit', '5:56 PM');
insert into Cours (NomDeCours, TempsCours) values ('gym', '7:33 AM');
insert into Cours (NomDeCours, TempsCours) values ('cardio', '10:36 AM');
insert into Cours (NomDeCours, TempsCours) values ('crossfit', '9:35 AM');
insert into Cours (NomDeCours, TempsCours) values ('cardio', '6:46 PM');
insert into Cours (NomDeCours, TempsCours) values ('cardio', '9:45 AM');
insert into Cours (NomDeCours, TempsCours) values ('gym', '5:05 PM');
insert into Cours (NomDeCours, TempsCours) values ('gym', '2:06 PM');
insert into Cours (NomDeCours, TempsCours) values ('crossfit', '4:08 PM');
insert into Cours (NomDeCours, TempsCours) values ('gym', '4:56 PM');
insert into Cours (NomDeCours, TempsCours) values ('crossfit', '8:50 AM');
insert into Cours (NomDeCours, TempsCours) values ('gym', '7:39 PM');
insert into Cours (NomDeCours, TempsCours) values ('cardio', '6:49 AM');
insert into Cours (NomDeCours, TempsCours) values ('crossfit', '12:09 PM');
insert into Cours (NomDeCours, TempsCours) values ('gym', '9:38 AM');
insert into Cours (NomDeCours, TempsCours) values ('cardio', '10:53 AM');
insert into Cours (NomDeCours, TempsCours) values ('gym', '7:30 PM');
insert into Cours (NomDeCours, TempsCours) values ('crossfit', '6:57 AM');
insert into Cours (NomDeCours, TempsCours) values ('crossfit', '8:21 AM');
insert into Cours (NomDeCours, TempsCours) values ('gym', '12:15 PM');
insert into Cours (NomDeCours, TempsCours) values ('gym', '12:52 PM');
insert into Cours (NomDeCours, TempsCours) values ('gym', '3:35 PM');
insert into Cours (NomDeCours, TempsCours) values ('cardio', '12:57 PM');
insert into Cours (NomDeCours, TempsCours) values ('crossfit', '3:45 PM');
insert into Cours (NomDeCours, TempsCours) values ('cardio', '7:22 AM');
insert into Cours (NomDeCours, TempsCours) values ('crossfit', '8:11 AM');
insert into Cours (NomDeCours, TempsCours) values ('cardio', '4:13 PM');
insert into Cours (NomDeCours, TempsCours) values ('gym', '10:38 AM');
insert into Cours (NomDeCours, TempsCours) values ('crossfit', '7:30 AM');
insert into Cours (NomDeCours, TempsCours) values ('crossfit', '5:58 PM');
insert into Cours (NomDeCours, TempsCours) values ('gym', '3:08 PM');
insert into Cours (NomDeCours, TempsCours) values ('crossfit', '6:05 PM');
insert into Cours (NomDeCours, TempsCours) values ('crossfit', '3:48 PM');
insert into Cours (NomDeCours, TempsCours) values ('gym', '6:52 PM');
insert into Cours (NomDeCours, TempsCours) values ('cardio', '9:32 AM');
insert into Cours (NomDeCours, TempsCours) values ('cardio', '6:36 AM');
insert into Cours (NomDeCours, TempsCours) values ('cardio', '9:05 AM');
insert into Cours (NomDeCours, TempsCours) values ('cardio', '6:04 AM');
insert into Cours (NomDeCours, TempsCours) values ('crossfit', '4:50 PM');
insert into Cours (NomDeCours, TempsCours) values ('crossfit', '7:15 PM');
insert into Cours (NomDeCours, TempsCours) values ('gym', '9:09 AM');
insert into Cours (NomDeCours, TempsCours) values ('cardio', '6:36 AM');
insert into Cours (NomDeCours, TempsCours) values ('crossfit', '8:17 AM');
insert into Cours (NomDeCours, TempsCours) values ('cardio', '4:07 PM');
insert into Cours (NomDeCours, TempsCours) values ('cardio', '2:31 PM');
insert into Cours (NomDeCours, TempsCours) values ('gym', '11:57 AM');
insert into Cours (NomDeCours, TempsCours) values ('gym', '12:25 PM');
insert into Cours (NomDeCours, TempsCours) values ('crossfit', '5:30 PM');
insert into Cours (NomDeCours, TempsCours) values ('cardio', '5:28 PM');
insert into Cours (NomDeCours, TempsCours) values ('gym', '1:40 PM');
insert into Cours (NomDeCours, TempsCours) values ('cardio', '3:27 PM');
insert into Cours (NomDeCours, TempsCours) values ('crossfit', '7:03 PM');
insert into Cours (NomDeCours, TempsCours) values ('crossfit', '6:24 AM');
insert into Cours (NomDeCours, TempsCours) values ('crossfit', '3:22 PM');
insert into Cours (NomDeCours, TempsCours) values ('cardio', '4:57 PM');
insert into Cours (NomDeCours, TempsCours) values ('crossfit', '8:13 AM');
insert into Cours (NomDeCours, TempsCours) values ('gym', '11:23 AM');
insert into Cours (NomDeCours, TempsCours) values ('gym', '9:51 AM');
insert into Cours (NomDeCours, TempsCours) values ('cardio', '7:25 AM');
insert into Cours (NomDeCours, TempsCours) values ('gym', '7:26 PM');
insert into Cours (NomDeCours, TempsCours) values ('cardio', '2:38 PM');
insert into Cours (NomDeCours, TempsCours) values ('gym', '10:22 AM');
insert into Cours (NomDeCours, TempsCours) values ('gym', '10:07 AM');
insert into Cours (NomDeCours, TempsCours) values ('cardio', '6:02 AM');
insert into Cours (NomDeCours, TempsCours) values ('gym', '9:40 AM');
insert into Cours (NomDeCours, TempsCours) values ('cardio', '3:41 PM');
insert into Cours (NomDeCours, TempsCours) values ('gym', '12:38 PM');
insert into Cours (NomDeCours, TempsCours) values ('gym', '8:23 AM');
insert into Cours (NomDeCours, TempsCours) values ('gym', '12:12 PM');
insert into Cours (NomDeCours, TempsCours) values ('cardio', '5:30 PM');
insert into Cours (NomDeCours, TempsCours) values ('crossfit', '11:40 AM');
insert into Cours (NomDeCours, TempsCours) values ('gym', '2:46 PM');
insert into Cours (NomDeCours, TempsCours) values ('crossfit', '10:02 AM');
insert into Cours (NomDeCours, TempsCours) values ('gym', '4:10 PM');
insert into Cours (NomDeCours, TempsCours) values ('cardio', '7:30 AM');
insert into Cours (NomDeCours, TempsCours) values ('cardio', '6:13 AM');
insert into Cours (NomDeCours, TempsCours) values ('cardio', '12:37 PM');
insert into Cours (NomDeCours, TempsCours) values ('crossfit', '12:11 PM');
insert into Cours (NomDeCours, TempsCours) values ('crossfit', '1:32 PM');
insert into Cours (NomDeCours, TempsCours) values ('cardio', '11:31 AM');
insert into Cours (NomDeCours, TempsCours) values ('gym', '7:13 PM');
insert into Cours (NomDeCours, TempsCours) values ('cardio', '3:31 PM');
insert into Cours (NomDeCours, TempsCours) values ('gym', '6:27 AM');
insert into Cours (NomDeCours, TempsCours) values ('crossfit', '5:57 PM');
insert into Cours (NomDeCours, TempsCours) values ('cardio', '6:02 AM');
insert into Cours (NomDeCours, TempsCours) values ('cardio', '1:14 PM');
insert into Cours (NomDeCours, TempsCours) values ('gym', '11:57 AM');
insert into Cours (NomDeCours, TempsCours) values ('crossfit', '2:21 PM');
insert into Cours (NomDeCours, TempsCours) values ('cardio', '4:12 PM');
insert into Cours (NomDeCours, TempsCours) values ('gym', '7:52 PM');
insert into Cours (NomDeCours, TempsCours) values ('gym', '8:01 AM');
insert into Cours (NomDeCours, TempsCours) values ('gym', '1:38 PM');
insert into Cours (NomDeCours, TempsCours) values ('crossfit', '1:11 PM');
insert into Cours (NomDeCours, TempsCours) values ('crossfit', '6:52 PM');
insert into Cours (NomDeCours, TempsCours) values ('gym', '6:46 AM');
insert into Cours (NomDeCours, TempsCours) values ('gym', '7:22 AM');
insert into Cours (NomDeCours, TempsCours) values ('cardio', '11:40 AM');
insert into Cours (NomDeCours, TempsCours) values ('cardio', '2:04 PM');
insert into Cours (NomDeCours, TempsCours) values ('gym', '4:36 PM');
insert into Cours (NomDeCours, TempsCours) values ('cardio', '7:30 AM');
insert into Cours (NomDeCours, TempsCours) values ('cardio', '5:43 PM');
insert into Cours (NomDeCours, TempsCours) values ('gym', '10:48 AM');
insert into Cours (NomDeCours, TempsCours) values ('cardio', '7:32 AM');



INSERT INTO MembreCours (MembreID, CoursID)
VALUES 
	(1,1),
	(2,1),
	(3,1),
	(4,1),
	(5,1),
	(6,1),
	(8,1),
	(9,1),
	(10,1),
	(11,1),
	(12,1),
	(13,1),
	(14,1),
	(15,1),
	(16,1),
	(17,1),
	(18,1),
	(19,1),
	(20,1),
	(21,2),
	(22,2),
	(23,2),
	(24,2),
	(25,2),
	(26,2),
	(27,2),
	(28,2),
	(29,2),
	(30,2),
	(31,2),
	(32,2),
	(33,2),
	(34,2),
	(35,3),
	(36,3),
	(37,3),
	(38,3),
	(39,3),
	(40,3),
	(41,3),
	(42,3),
	(43,3),
	(44,3),
	(45,3),
	(46,3),
	(47,3),
	(48,3),
	(49,3),
	(50,3),
	(51,3),
	(52,3),
	(53,3),
	(54,3),
	(55,3),
	(56,4),
	(57,4),
	(58,4),
	(59,4),
	(60,4),
	(61,4),
	(62,4),
	(63,4),
	(64,4),
	(65,4),
	(66,4),
	(67,4),
	(68,4),
	(69,4),
	(70,4),
	(71,4),
	(72,4),
	(73,4),
	(74,4),
	(75,4);

	
	


	


